apiVersion: v1
kind: Secret
metadata:
  name: neural-pulse-secrets
  namespace: gp-engine-mizzou-dcps
type: Opaque
data:
  WANDB_API_KEY: YzdlYTMxZTU3OTNiYTQ0ZDk1ZDkxODQwYTEwZDcwOTM3OGViMmQ5ZA==
  WANDB_ENTITY: a2h1cnJhbWtoYWxpbA==
  WANDB_PROJECT: bmV1cmFsLXB1bHNl
  HF_TOKEN: aGZfSXB5RmN3c2VPakVMcVVvTXBIc2J3b3hMZERTSXJoYWd3Qg==
  KAGGLE_USERNAME: a2h1cnJhbWtoYWxpbA==
  KAGGLE_KEY: ZDVkMmQyODFjMGZlYjM3Njc4NGNkN2NlZTFmMzNhYTc=
  GOOGLE_CLOUD_PROJECT_ID: bmV1cmFsLXB1bHNl
  GEMINI_API_KEY: QUl6YVN5QllCc09sT1dVXzh6b0d3amJsUkpKb2lvNVRVNURTTkgw
  LLM_TOKEN: RGpSWXZHNFhJcGJ6Znl2WnZJZ09aN2V5UjJHb2dmSzg=
